MittalSquash/MittalSquash/Controllers/ResourcesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MittalSquash.Data;

namespace MittalSquash.Controllers
{
    [Authorize]
    public class ResourcesController : Controller
    {
        private MittalSquashEntities db = new MittalSquashEntities();

        // GET: Resources
        public ActionResult Index()
        {
            var resources = db.Resources.Include(r => r.AspNetUser);
            return View(resources.ToList());
        }

        // GET: Resources/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resource resource = db.Resources.Find(id);
            if (resource == null)
            {
                return HttpNotFound();
            }
            return View(resource);
        }

        // GET: Resources/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.AspNetUsers.Where(x=>x.UserName == User.Identity.Name), "Id", "Email");
            return View();
        }

        // POST: Resources/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ResourceId,Name,CreateDate,UserId,isActive")] Resource resource)
        {
            resource.CreateDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Resources.Add(resource);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", resource.UserId);
            return View(resource);
        }

        // GET: Resources/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resource resource = db.Resources.Find(id);
            if (resource == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", resource.UserId);
            return View(resource);
        }

        // POST: Resources/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ResourceId,Name,CreateDate,UserId,isActive")] Resource resource)
        {
            if (ModelState.IsValid)
            {
                db.Entry(resource).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", resource.UserId);
            return View(resource);
        }

        // GET: Resources/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resource resource = db.Resources.Find(id);
            if (resource == null)
            {
                return HttpNotFound();
            }
            return View(resource);
        }

        // POST: Resources/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Resource resource = db.Resources.Find(id);
            db.Resources.Remove(resource);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MittalSquash/MittalSquash/Views/Resources/Create.cshtml
@model MittalSquash.Data.Resource

@{
    ViewBag.Title = "Create";
}

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area">
    <!-- Breadcumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Resource</a></li>
        </ol>
    </nav>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### Blog Area Start ##### -->
<section class="blog-area blog-page" style="padding-top: 20px">
    <div class="container-fluid">
        <div class="row">
            <!-- Single Blog Area -->
            <div class="col-12">
                <div class="single-blog-area mb-100 wow fadeInUp" data-wow-delay="500ms">
                    <!-- Blog Content -->
                    <div class="blog-content">
                        <a href="#" class="blog-headline">
                            <h4>Add Resource</h4>
                            <hr/>
                        </a>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                @*<div class="form-group">
                                    @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>*@

                                <div class="form-group">
                                    @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            @Html.EditorFor(model => model.isActive)
                                            @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn clever-btn" />
                                        <a href="#" class="btn clever-btn" onclick="window.location = '@Url.Action("Index", "Resources")'">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        }

                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- ##### Blog Area End ##### -->

MittalSquash/MittalSquash/Views/Resources/Delete.cshtml
@model MittalSquash.Data.Resource

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Resource</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MittalSquash/MittalSquash/Views/Resources/Details.cshtml
@model MittalSquash.Data.Resource

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Resource</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ResourceId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MittalSquash/MittalSquash/Views/Resources/Edit.cshtml
@model MittalSquash.Data.Resource

@{
    ViewBag.Title = "Edit";
}

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area">
    <!-- Breadcumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Resource</a></li>
        </ol>
    </nav>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### Blog Area Start ##### -->
<section class="blog-area blog-page" style="padding-top: 20px">
    <div class="container-fluid">
        <div class="row">
            <!-- Single Blog Area -->
            <div class="col-12">
                <div class="single-blog-area mb-100 wow fadeInUp" data-wow-delay="500ms">
          
                    <!-- Blog Content -->
                    <div class="blog-content">
                        <a href="#" class="blog-headline">
                            <h4>Edit Resource</h4>
                            <hr/>
                        </a>


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                              
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.ResourceId)

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                @Html.HiddenFor(m => m.UserId)
                                @Html.HiddenFor(m => m.CreateDate)

                                <div class="form-group">
                                    @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            @Html.EditorFor(model => model.isActive)
                                            @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn clever-btn" />
                                        <a href="#" class="btn clever-btn" onclick="window.location = '@Url.Action("Index", "Resources")'">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        }

                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- ##### Blog Area End ##### -->

MittalSquash/MittalSquash/Views/Resources/Index.cshtml
@model IEnumerable<MittalSquash.Data.Resource>

@{
    ViewBag.Title = "Index";
}

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area">
    <!-- Breadcumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Resources</a></li>
        </ol>
    </nav>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### Blog Area Start ##### -->
<section class="blog-area blog-page" style="padding-top: 20px">
    <div class="container-fluid">
        <div class="row">
            <!-- Single Blog Area -->
            <div class="col-12">
                <div class="single-blog-area mb-100 wow fadeInUp" data-wow-delay="500ms">
           
                    <!-- Blog Content -->
                    <div class="blog-content">
                        <a href="#" class="blog-headline">
                            <h4>Resources</h4>
                      
                        </a>
                        <a href="#" class="btn clever-btn pull-right" onclick="window.location = '@Url.Action("Create", "Resources")'">Create New</a>
     <br/><br/>
                        <table class="table">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    <label>Created By</label>
                                </th>
                                <th>
                                    <label>Created Date</label>
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.isActive)
                                </th>
                              
                                <th></th>
                            </tr>

                            @foreach (var item in Model) {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.AspNetUser.Email)
                                    </td>
                                    <td>
                                        @item.CreateDate.ToString("dddd, dd MMMM yyyy")
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.isActive)
                                    </td>
                               
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id=item.ResourceId })
                                    </td>
                                </tr>
                            }

                        </table>

                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- ##### Blog Area End ##### -->