MittalSquash/MittalSquash/Controllers/WorkingHoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MittalSquash.Data;

namespace MittalSquash.Controllers
{
    [Authorize]
    public class WorkingHoursController : Controller
    {
        private MittalSquashEntities db = new MittalSquashEntities();

        // GET: WorkingHours
        public ActionResult Index()
        {
            return View(db.WorkingHours.ToList());
        }

        // GET: WorkingHours/Details/5
        public ActionResult Details(int? id) // edit event handler working hours
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkingHour workingHour = db.WorkingHours.Find(id);
            if (workingHour == null)
            {
                return HttpNotFound();
            }
            return View(workingHour);
        }

        // GET: WorkingHours/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WorkingHours/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,WorkDay,DayOfWeek,StartTimeHour,StartTimeMinute,EndTimeHour,EndTimeMinute,isActive")] WorkingHour workingHour) //bind variables to db
        {
            if (ModelState.IsValid)
            {
                db.WorkingHours.Add(workingHour);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(workingHour);
        }

        // GET: WorkingHours/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkingHour workingHour = db.WorkingHours.Find(id);
            if (workingHour == null)
            {
                return HttpNotFound();
            }
            return View(workingHour);
        }

        // POST: WorkingHours/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,WorkDay,DayOfWeek,StartTimeHour,StartTimeMinute,EndTimeHour,EndTimeMinute,isActive")] WorkingHour workingHour)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workingHour).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(workingHour);
        }

        // GET: WorkingHours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkingHour workingHour = db.WorkingHours.Find(id);
            if (workingHour == null)
            {
                return HttpNotFound();
            }
            return View(workingHour);
        }

        // POST: WorkingHours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkingHour workingHour = db.WorkingHours.Find(id);
            db.WorkingHours.Remove(workingHour);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MittalSquash/MittalSquash/Views/WorkingHours/Create.cshtml
@model MittalSquash.Data.WorkingHour

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WorkingHour</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayOfWeek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DayOfWeek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DayOfWeek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTimeHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTimeHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTimeHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTimeMinute, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTimeMinute, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTimeMinute, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTimeHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTimeHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTimeHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTimeMinute, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTimeMinute, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTimeMinute, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MittalSquash/MittalSquash/Views/WorkingHours/Delete.cshtml
@model MittalSquash.Data.WorkingHour

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkingHour</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorkDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DayOfWeek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayOfWeek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTimeHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTimeHour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTimeMinute)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTimeMinute)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTimeHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTimeHour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTimeMinute)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTimeMinute)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MittalSquash/MittalSquash/Views/WorkingHours/Details.cshtml
@model MittalSquash.Data.WorkingHour

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>WorkingHour</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorkDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DayOfWeek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayOfWeek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTimeHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTimeHour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTimeMinute)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTimeMinute)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTimeHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTimeHour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTimeMinute)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTimeMinute)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MittalSquash/MittalSquash/Views/WorkingHours/Edit.cshtml
@model MittalSquash.Data.WorkingHour

@{
    ViewBag.Title = "Edit";
}

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area">
    <!-- Breadcumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Settings</a></li>
        </ol>
    </nav>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### Blog Area Start ##### -->
<section class="blog-area blog-page" style="padding-top: 20px">
    <div class="container-fluid">
        <div class="row">
            <!-- Single Blog Area -->
            <div class="col-12">
                <div class="single-blog-area mb-100 wow fadeInUp" data-wow-delay="500ms">
                    <img src="img/blog-img/2.jpg" alt="">
                    <!-- Blog Content -->
                    <div class="blog-content">
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <a href="#" class="blog-headline">
                                    <h4>Working Hours</h4>
                                    <hr/>
                                </a>
                            
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.HiddenFor(model => model.ID)

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.WorkDay, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.WorkDay, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                @Html.ValidationMessageFor(model => model.WorkDay, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.DayOfWeek, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.DayOfWeek, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                @Html.ValidationMessageFor(model => model.DayOfWeek, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label>Start Time</label>
                                            <div class="col-md-10">
                                                <table>
                                                    <tr>
                                                        <td>
                                                            @Html.EditorFor(model => model.StartTimeHour, new {htmlAttributes = new {@class = "form-control"}})
                                                            @Html.ValidationMessageFor(model => model.StartTimeHour, "", new {@class = "text-danger"})
                                                        </td>
                                                        <td>
                                                            @Html.EditorFor(model => model.StartTimeMinute, new {htmlAttributes = new {@class = "form-control"}})
                                                            @Html.ValidationMessageFor(model => model.StartTimeMinute, "", new {@class = "text-danger"})
                                                        </td>
                                                    </tr>
                                                </table>

                                            </div>
                                        </div>
                                   

                                        <div class="form-group">
                                            <label>End Time</label>
                                            <div class="col-md-10">
                                                <table>
                                                    <tr>
                                                        <td>
                                                            @Html.EditorFor(model => model.EndTimeHour, new {htmlAttributes = new {@class = "form-control"}})
                                                            @Html.ValidationMessageFor(model => model.EndTimeHour, "", new {@class = "text-danger"})
                                                        </td>
                                                        <td>
                                                            @Html.EditorFor(model => model.EndTimeMinute, new {htmlAttributes = new {@class = "form-control"}})
                                                            @Html.ValidationMessageFor(model => model.EndTimeMinute, "", new {@class = "text-danger"})
                                                        </td>
                                                    </tr>
                                                </table>

                                            </div>
                                        </div>
                                 

                                        <div class="form-group">
                                            <label>Active</label>
                                            <div class="col-md-10">
                                                <div class="checkbox">
                                                    @Html.EditorFor(model => model.isActive)
                                                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger",disabled = "disabled" })
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Save" class="btn clever-btn" />
                                                <a href="#" class="btn clever-btn" onclick="window.location = '@Url.Action("Index", "WorkingHours")'">Cancel</a>
                                            </div>
                                        </div>
                                    </div>
                                }

                       

                            </div>
                        </div>

            

                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- ##### Blog Area End ##### -->

MittalSquash/MittalSquash/Views/WorkingHours/Index.cshtml
@model IEnumerable<MittalSquash.Data.WorkingHour>

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area">
    <!-- Breadcumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Settings</a></li>
        </ol>
    </nav>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### Blog Area Start ##### -->
<section class="blog-area blog-page" style="padding-top: 20px">
    <div class="container-fluid">
        <div class="row">
            <!-- Single Blog Area -->
            <div class="col-12">
                <div class="single-blog-area mb-100 wow fadeInUp" data-wow-delay="500ms">
           
                    <!-- Blog Content -->

                    <div class="blog-content">
                        <a href="#" class="blog-headline">
                            <h4>Working Hours</h4>
                        </a>
                        @*<a href="#" class="btn clever-btn pull-right" onclick="window.location = '@Url.Action("Create", "WorkingHours")'">Create New</a>*@
                        <br /><br />
                        <table class="table">
                            <tr>
                                <th>
                                    <label>Work Day</label>
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DayOfWeek)
                                </th>
                                <th>
                                    <label>Start Time</label>
                                </th>
                                <th>
                                    <label>End Time</label>
                                </th>
                               
                                <th>
                                    @Html.DisplayNameFor(model => model.isActive)
                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.WorkDay)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DayOfWeek)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.StartTimeHour) :
                                        @Html.DisplayFor(modelItem => item.StartTimeMinute)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EndTimeHour) :
                                        @Html.DisplayFor(modelItem => item.EndTimeMinute)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.isActive)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) 
                                    </td>
                                </tr>
                            }

                        </table>

                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- ##### Blog Area End ##### -->