MittalSquash/MittalSquash/Controllers/BookingHomeController.cs
using MittalSquash.Data;
using MittalSquash.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MittalSquash.Controllers
{
    public class BookingHomeController : Controller
    {
        private readonly MittalSquashEntities db = new MittalSquashEntities();
        // GET: BookingHome
        public ActionResult Index(string date)
        {
            var now = string.IsNullOrEmpty(date) ? DateTime.Now : Convert.ToDateTime(date);

            var todayTimes = db.WorkingHours.FirstOrDefault(x => x.DayOfWeek == (int)now.DayOfWeek);
            var startHour = todayTimes.StartTimeHour;
            var endHour = todayTimes.EndTimeHour;

            //Current date data
            var data = db.Events.Where(x => x.EventDate == now.Date).GroupBy(g => g.ResourceId);

            ViewBag.CurrentFilter = now.Date.ToString("MM/dd/yyyy");

            var bookings = new List<Booking>();
            List<Resource> resources = new List<Resource>();
            resources.Add(new Resource() { ResourceId = 0, Name = "Time" });
            resources.AddRange(db.Resources);

            foreach (var resource in resources)
            {

                DateTime startDate = new DateTime(now.Year, now.Month, now.Day, startHour.Value, 0, 0);
                DateTime endDate = new DateTime(now.Year, now.Month, now.Day, endHour.Value, 0, 0);

                //Resource Data
                var resourceData = data.FirstOrDefault(x => x.Key == resource.ResourceId);

                var booking = new Booking() { Resource = resource, Date = now };
                var eventBookings = new List<EventBooking>();
                while (startDate < endDate)
                {
                    EventBooking eventBooking = new EventBooking();

                    if (resourceData != null)
                    {
                        var bookedEvent = resourceData.FirstOrDefault(x => x.EventTime == startDate.ToString("HH:mm"));

                        if (bookedEvent != null)
                        {
                            eventBooking.EventId = bookedEvent.EventId;
                            eventBooking.booked = true;
                            eventBooking.UserName = bookedEvent.AspNetUser.UserName;
                        }
                        else
                        {
                            eventBooking.EventId = 0;
                            eventBooking.booked = false;
                            eventBooking.isOwner = false;
                        }
                    }
                    else
                    {
                        eventBooking.EventId = 0;
                        eventBooking.booked = false;
                        eventBooking.isOwner = false;
                    }

                    eventBooking.Time = startDate.ToString("HH:mm tt");
                    eventBookings.Add(eventBooking);
                    startDate = startDate.AddMinutes(30);
                }

                booking.EventBookings = eventBookings;
                bookings.Add(booking);
            }

            return View(bookings);
        }
    }
}

MittalSquash/MittalSquash/Views/BookingHome/Index.cshtml
@model IEnumerable<MittalSquash.Models.Booking>
@{
    ViewBag.Title = "Index";
}
<style>
    .time {
        align-content: center;
    }
</style>

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area">
    <!-- Breadcumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Booking</a></li>
        </ol>
    </nav>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### Blog Area Start ##### -->
<section class="blog-area blog-page" style="padding-top: 20px">
    <div class="container-fluid">
        <div class="row">
            <!-- Single Blog Area -->
            <div class="col-12">
                <div class="single-blog-area  wow fadeInUp" data-wow-delay="250ms">
                    @using (Html.BeginForm("Index", "BookingHome", FormMethod.Get))
                    {
                        <div class="blog-content">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row">
                                        <div class="col-md-6 text-right">
                                            <label>Date</label>
                                        </div>
                                        <div class="col-md-6">
                                            <table>
                                                <tr>
                                                    <td>
                                                        <div class="input-group date" data-provide="datepicker">
                                                            @Html.TextBox("Date", ViewBag.CurrentFilter as string, new { @class = "form-control", @data_date_format = "mm/dd/yyyy", @readonly = "readonly" })
                                                            <div class="input-group-addon" style="padding: 10px; border: 1px solid silver">
                                                                <i class="fa fa-calendar"></i>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td style="padding-left: 30px">

                                                        <button class="btn btn-primary" type="submit">
                                                            <i class="fa fa-search"></i> SEARCH
                                                        </button>
                                                    </td>
                                                </tr>
                                            </table>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }



                </div>
            </div>

            <!-- Single Blog Area -->
            <div class="col-12">
                <div class="single-blog-area mb-100 wow fadeInUp" data-wow-delay="500ms">
                    <!-- Blog Content -->
                    <div class="blog-content">
                        <a href="#" class="blog-headline">
                            <h4 class="pull-right"><i class="fa fa-calendar"></i> @Model.FirstOrDefault().Date.ToString("D")</h4>
                            <table>
                                <tr>
                                    <td style="min-width: 150px">
                                        <h4>Scheduler</h4>
                                    </td>
                                    <td class="bg-warning" style="min-width: 100px; height: 45px; align-content: center; padding-left: 20px"> BOOKED</td>
                                </tr>
                            </table>

                            <hr />

                        </a>
                        <div class="table-responsive" style="overflow:auto">
                            <table style="width: 100%">
                                <tr>
                                    @foreach (var modelBooking in Model)
                                    {
                                        <td style="padding: 10px">
                                            <table class="table table-hover" style="width: 100%; margin: 10px">
                                                <tr>
                                                    <th>@modelBooking.Resource.Name </th>
                                                </tr>
                                                @foreach (var eventBooking in modelBooking.EventBookings)
                                                {
                                                    if (modelBooking.Resource.ResourceId == 0)
                                                    {
                                                        <tr>
                                                            <td class="time" style="height: 45px; padding: 0;">
                                                                <b class="time">@eventBooking.Time</b>

                                                            </td>
                                                        </tr>
                                                    }
                                                    else
                                                    {
                                                        <tr>
                                                            @if (eventBooking.booked)
                                                            {
                                                                if (eventBooking.isOwner)
                                                                {
                                                                    <td style="min-width: 150px; height: 45px; padding: 0">
                                                                        <table style="width: 100%">
                                                                            <tr>
                                                                                <td class="bg-success" style="min-width: 10px; height: 45px; padding: 0; background-color: silver"></td>
                                                                                <td style="min-width: 140px; height: 45px; padding: 10px">
                                                                                    <i class="fa fa-calendar"> Booked</i>
                                                                                </td>
                                                                            </tr>
                                                                        </table>
                                                                    </td>
                                                                }
                                                                else
                                                                {
                                                                    <td class="bg-warning" style="min-width: 150px; height: 45px; padding: 0; background-color: silver"></td>
                                                                }
                                                            }
                                                            else
                                                            {

                                                                <td style="min-width: 150px; height: 45px; padding: 0">
                                                                </td>
                                                            }


                                                        </tr>
                                                    }
                                                }
                                            </table>
                                        </td>
                                    }

                                </tr>
                            </table>
                        </div>

                    </div>
                </div>
            </div>

        </div>

    </div>
</section>


<script type="text/javascript">

    $('.datepicker').datepicker({
        format: 'yyyy/MM/dd',
        startDate: '-3d'
    });


</script>